### ISSUE TITLE
Single license file for all the softwares 

### ISSUE THREAD

**Issue by shrenujgandhi** [SoftwareEngineeringToolDemos/ICSE-2011-ReAssert#10]
The rubric states that there should be a single license file that contains all the licenses for the software contained in the VM.

**Comment by gsrajadh** [comment]
Hi,
I have created a single license file and uploaded in my VM. Should I mail you the link?

**Comment by shrenujgandhi** [comment]
I guess it is not required at this point. You can close the issue as you have corrected it.
