### ISSUE TITLE
User gets logged out of the VM 

### ISSUE THREAD

**Issue by shrenujgandhi** [SoftwareEngineeringToolDemos/ICSE-2011-ReAssert#11]
If the guest VM is left idle for 15-20mins, then machine automatically logs out.

![log out issue](https://cloud.githubusercontent.com/assets/13962371/10570852/5ca765f6-75ed-11e5-84c2-48747432df76.png)

**Comment by gsrajadh** [comment]
Hi, I have worked on this. Should I give you my updated VM? As you need to submit my VM link to the professor.

**Comment by shrenujgandhi** [comment]
Please send the updated link. I will be  able to review it by tomorrow afternoon. But if you have resolved the issue, I am sure you can close this one.

**Comment by gsrajadh** [comment]
Hi,
Its on the same google drive. Just download it from there and review it.
