### ISSUE TITLE
Extra spacing

### ISSUE THREAD

**Issue by shrenujgandhi** [SoftwareEngineeringToolDemos/ICSE-2011-ReAssert#4]
The spacing between the phrase "add the following update site:" and the following link should be removed.

**Comment by shrenujgandhi** [comment]
Should there be a space after the paragraph containing the link "http://mir.cs.illinois.edu/reassert/download/update/."?

**Comment by gsrajadh** [comment]
Hi, just wanted to confirm are you resolving this issue?

**Comment by shrenujgandhi** [comment]
The latest commit resolves this issue.
