### ISSUE TITLE
Should the link be highlighted in the installation instruction?

### ISSUE THREAD

**Issue by shrenujgandhi** [SoftwareEngineeringToolDemos/ICSE-2011-ReAssert#6]
Since the user has to paste the site "http://mir.cs.illinois.edu/reassert/download/update/", should it be highlighted?

**Comment by gsrajadh** [comment]
I have already used a different font color for it. Can you please mention which part of the rubric says that links should be highlighted?

**Comment by shrenujgandhi** [comment]
My question originally meant that since the link it to be pasted, is doesn't seem natural to provide it as a hyperlink. Can't we provide the link in plain text, instead?

**Comment by gsrajadh** [comment]
Hi, can you check if the latest commit seems okay to you?

**Comment by shrenujgandhi** [comment]
Yes, the latest version seem okay. We can close this issue.
