### ISSUE TITLE
Audio in YouTube demo?

### ISSUE THREAD

**Issue by shrenujgandhi** [SoftwareEngineeringToolDemos/ICSE-2011-ReAssert#9]
Although not compulsory, please confirm whether it is okay to have the demo without the audio.

**Comment by gsrajadh** [comment]
Hi,
I have shown the instruction through the text file. Can you please show me if the professor has mentioned anywhere about the demo having audio?

**Comment by gsrajadh** [comment]
Hi, Professor has said its fine on Piazza. So can I close this issue?

**Comment by shrenujgandhi** [comment]
Affirmative.
